### ISSUE TITLE
Add TrueCrypt

### ISSUE THREAD

**Issue by UtahDave** [saltstack/salt-winrepo#14]

**Comment by DavidJFelix** [comment]
Probably no longer valid.

**Comment by TheBigBear** [comment]
I disagree, and so do many others, it has been audited and this version appears 'clean'. can we not let the users decide IF they want to install this or not? same applies to #267 
I for one need it installed on all my laptops
ping @UtahDave

**Comment by UtahDave** [comment]
I think there's enough users of truecrypt still to warrant its inclusion here. We should probably keep an eye on the project though and remove it from this repo if they remove their downloads or a severe vulnerability is exposed that they're not going to fix.

**Comment by TheBigBear** [comment]
My thoughts exactly. Thanks.
