### ISSUE TITLE
https link does not work for TLS secured DL for teamviewer

### ISSUE THREAD

**Issue by TheBigBear** [saltstack/salt-winrepo#142]
I had a TLS https: link for teamviewer and it would not work. It either crashed or gave up, giving an ssl cert error.
```
    The minion function caused an exception: Traceback (most recent call last):
      File "salt/minion.py", line 1019, in _thread_return
      File "salt/modules/win_pkg.py", line 558, in install
      File "salt/modules/cp.py", line 328, in cache_file
      File "salt/fileclient.py", line 149, in cache_file
      File "salt/fileclient.py", line 591, in get_url
      File "requests/api.py", line 55, in get
      File "requests/api.py", line 44, in request
      File "requests/sessions.py", line 456, in request
      File "requests/sessions.py", line 559, in send
      File "requests/adapters.py", line 382, in send
    SSLError: [Errno 185090050] _ssl.c:340: error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib
```
That happens with the folowing https installer URL, but if you remove the 's' and do a http:// DL it works.

```
teamviewer:
  10.0.38475:
    installer: 'https://downloadeu1.teamviewer.com/download/TeamViewer_Setup_en.exe'
    full_name: 'TeamViewer 10'
    reboot: False
    install_flags: '/S'
    uninstaller: '%ProgramFiles(x86)%\TeamViewer\uninstall.exe'
    uninstall_flags: '/S'
``` 
Is this to be expected or a feature? ;-)

**Comment by UtahDave** [comment]
Yeah, this is a known bug. We'll have an updated version of requests in 2014.7.2 and that https downloads should resume working.

**Comment by TheBigBear** [comment]
> On 6 Feb 2015, at 17:30, David Boucha <notifications@github.com> wrote:
> 
> Yeah, this is a known bug. We'll have an updated version of requests in 2014.7.2 and that https downloads should resume working.
> 
Ok, cool, thanks. I have switched the URL in the teamviewer PR to be http only for now. Will flip it back to https , after the known bug is fixed and tested.

**Comment by TheBigBear** [comment]
re-tested and https now works again, I have switched this back to a https download link and updated the version to be the most current one.
