### ISSUE TITLE
gow.sls might suffer from current https or SSL issues

### ISSUE THREAD

**Issue by TheBigBear** [saltstack/salt-winrepo#148]
I found that the https link is suffering from some sort of TLS SSL issue, I assume it is the same issue that affected me the other day. on anohter package where @UtahDave said it was the SSL setup and a "known issue" and would get fixed 'soon' .

So I will re-test when the new SSL setup is in. Two workarounds in the meantime. 1st try a simple http link instead. If that does not solve it . download it manually and place it in your masters salt://win/repo/gow dir and refer to a salt link instead of the http one for now. 
Will keep monitoring this one and comment on the ticket if things change.

**Comment by TheBigBear** [comment]
is this same or different issue as I had with teamviewer download? #142

**Comment by UtahDave** [comment]
yes, this is the same https issue. We're testing the fix for it today.

**Comment by TheBigBear** [comment]
ok, re-tested this and https now works again
