### ISSUE TITLE
JRE download requires oracle accept

### ISSUE THREAD

**Issue by DavidJFelix** [saltstack/salt-winrepo#215]
Affects: Java JDK and JRE downloads
Expected: JRE url retrieves installer
Observed: JDK and JRE url is not directly accessible in browser. It requires a cookie telling oracle that you accept their license.

It seems CPU-z has a similar cookie requirement. Might be a place to grow the winrepo module to allow specifying cookie values to pass in a request.

**Comment by TheBigBear** [comment]
@DavidJFelix what I have done as a workaround fornow, is, I changed the sls file to point to ```salt://win/repo``` on the master and have the admins download and upload to salt master manually. It adds an extra steps, but once done on the master still allows the windows installer to be installed on as many minions as you like.
see the salt winrepo cURL.sls file https://github.com/saltstack/salt-winrepo/blob/master/curl.sls as an example of that workaround.

**Comment by DavidJFelix** [comment]
Okay some notes for myself and posterity about this effort. I just dug through the salt source code and I somehow managed to come out clean (holy shit).

So. Assuming winrepo wants to support these and not just push them out to formulas, we need cookie values. My proposal for yaml notation for this would be:

```yaml
oracle-java:
  8:
    installer:
        - url: http://download.oracle.com/otn-pub/java/jdk/8u60-b27/jdk-8u60-windows-x64.exe
        - cookies:
          - oraclelicense: accept-securebackup-cookie
```
etc

Now this poses a few issues to current winrepo logic.

First: Installer would need to be overloaded to handle a dictionary in addition to a basic url. At the time of writing, [this commit line number](https://github.com/saltstack/salt/blob/c390e812d8ce19595b0a78b5f8918f4f464055a5/salt/modules/win_pkg.py#L530) shows where it is.

Now, of course it's not that simple. We'd have to percolate the changes up a bit too. Since win_pkg calls into the cache, [here](https://github.com/saltstack/salt/blob/c390e812d8ce19595b0a78b5f8918f4f464055a5/salt/modules/win_pkg.py#L548) there'd probably have to be a new call. Something like "cache file with cookie". Naming aside, that would mean that the `cp` module has to change as well. Mimic [this function](https://github.com/saltstack/salt/blob/c390e812d8ce19595b0a78b5f8918f4f464055a5/salt/modules/cp.py#L339) to pass the cookie up to the fileclient [here](https://github.com/saltstack/salt/blob/c390e812d8ce19595b0a78b5f8918f4f464055a5/salt/modules/cp.py#L365). That means a mimic of [this function](https://github.com/saltstack/salt/blob/c390e812d8ce19595b0a78b5f8918f4f464055a5/salt/fileclient.py#L139) in the fileclient so that instead of calling [get_url on itself](https://github.com/saltstack/salt/blob/c390e812d8ce19595b0a78b5f8918f4f464055a5/salt/fileclient.py#L154), it instead calls the new version of `get_url` which now has an option for cookies. Cookies are held until [this line](https://github.com/saltstack/salt/blob/c390e812d8ce19595b0a78b5f8918f4f464055a5/salt/fileclient.py#L611) where we pass them into the `salt.utils.http.query` client function that has an optional argument for a cookie jar, as shown [here](https://github.com/saltstack/salt/blob/c390e812d8ce19595b0a78b5f8918f4f464055a5/salt/utils/http.py#L98).

Hope this helps me of the future, or any person feeling up to the challenge. Personally I believe either this change goes through or these packages have no place in winrepo, as they can't be reasonably downloaded from the internet like the rest. For the time being, I'll hack the formula option into my java formula so that it doesn't rely on winrepo. I'll let you know when I have that complete and show it here to determine the viability of the change I outlined above.

**Comment by DavidJFelix** [comment]
I'm closing this for the following reasons:

* I don't intend to do any work to fix this
* I am not concerned with it getting fixed
* It seems this issue may be outdated
  - Last mention was 2016
  - Oracle JRE is even more restrictive in 2018, to the point that this may be totally invalid now

I welcome anyone who evaluates this and finds it to still be relevant to reopen it
