### ISSUE TITLE
a number of winrepo issues have been resolved and should be closed

### ISSUE THREAD

**Issue by TheBigBear** [saltstack/salt-winrepo#249]
ping @UtahDave, the following salt winrepo issues have actually been resolved, but weren't closed when the code was committted.
In the interest of cutitng down on "clutter' in the active issues list, can they please be closed?
I have commented on each individually, which commit it was that closed/resolved the issue.

Add WinSCP #3 
https://github.com/saltstack/salt-winrepo/issues/3

Add Git #4 
https://github.com/saltstack/salt-winrepo/issues/4

Add OpenOffice #5 
https://github.com/saltstack/salt-winrepo/issues/5

Add Gimp #8 
https://github.com/saltstack/salt-winrepo/issues/8

Add LibreOffice #13 
https://github.com/saltstack/salt-winrepo/issues/13

Add PDFCreator #15 
https://github.com/saltstack/salt-winrepo/issues/15

Add TightVNC #16 
https://github.com/saltstack/salt-winrepo/issues/16

Add MySQL #24 
https://github.com/saltstack/salt-winrepo/issues/24

Putty URL needs updating. #41 
https://github.com/saltstack/salt-winrepo/issues/41

gpg4win-light.sls fails to install silently #113 
https://github.com/saltstack/salt-winrepo/issues/113

ultravnc_x86.sls is malformed - breaks winrepo.genrepo #157 
https://github.com/saltstack/salt-winrepo/issues/157

Thanks in advance.

**Comment by UtahDave** [comment]
awesome!  Thanks for compiling this list!

**Comment by UtahDave** [comment]
Done. Thanks again!
