### ISSUE TITLE
salt-minion fullname does not match installed name

### ISSUE THREAD

**Issue by carlpett** [saltstack/salt-winrepo#487]
The salt-minion.sls file states the full name with a version number prefixed by a 'v':

```salt-minion:
  2015.8.0rc3:
    full_name: 'Salt Minion v2015.8.0rc3'
    #...
  2015.5.3-2:
    full_name: 'Salt Minion v2015.5.3-2'
```

However, at least when installed on my machines (Win2012R2 datacenter ed), the name is `Salt Minion 2015.3.2`, without the 'v'. Is this something that is due to my machines, or did the spelling change at some point and there was a batch change to the file?

**Comment by TheBigBear** [comment]
@carlpett Thanks for reporting this. 

I have batch reverted this back to the names without the leading 'v' in front of the version number. 

I couldn't find where he error was introduced. It was quite possibly wrong from the start.

Please re-open this, if this did not solve it for you?

**Comment by carlpett** [comment]
@TheBigBear That solves it just fine, thank you :)
