### ISSUE TITLE
Feature request: Checksums

### ISSUE THREAD

**Issue by DavidJFelix** [saltstack/salt-winrepo#492]
We're fanning work out to a variety of servers of a variety of security and reliability. It sure would be nice to be able to specify a checksum on the installer/uninstaller to ensure that it's the one we expect before haphazardly running it.

**Comment by m03** [comment]
@DavidJFelix , I added something like that on the develop Salt branch a couple of weeks ago. See the source_hash parameter here:

https://docs.saltstack.com/en/develop/topics/windows/windows-package-manager.html

https://github.com/saltstack/salt/blob/develop/salt/modules/win_pkg.py
