### ISSUE TITLE
Add OpenOffice

### ISSUE THREAD

**Issue by UtahDave** [saltstack/salt-winrepo#5]

**Comment by TheBigBear** [comment]
OpenOffice is now in a PR ready for merging. https://github.com/saltstack/salt-winrepo/pull/99, so this can be closed now. 
ping @UtahDave

**Comment by TheBigBear** [comment]
commit b71f0a8bf064c75ae59f1ae7e76b1654de943b75 by @TheBigBear fixed this issue, it can be closed
