### ISSUE TITLE
Inconsistent naming for 64/32bit packages

### ISSUE THREAD

**Issue by DavidJFelix** [saltstack/salt-winrepo#504]
Some x64 packages have an `_x64` suffix to match the `_x86` being used for 32 bit packages, but some do not.

Wireshark does not, Python does. There are other examples.

**Comment by TheBigBear** [comment]
@DavidJFelix well spotted. ;-) 
Actually I think this might be allrigth and may make some sense? Let me try to explain.

Point 1 is that the distinction between x86 and x64 pkgs is badly broken when it comes to any minion < 2015.8 (i.e. all currently released minions), It works for most pkgs to get at least a version installed, often not the right one - moslty it wiil end up installing the x86 one everywhere, but when it comes to un-installing, it mostly fails. BUT in rel. >= 2015.8 this is going to change and all pkgs will have but a single name as some jinja2 code will determine whether one is on a 32-bit or 64-bit machine and install the right version accordingly.

This is great, but now we have a new probelm, most pkgs are not going to be problematic and generally speaking, if they have a 64-bit version then it would be perfeclty fine and good to install that 64-bit version. But there are pkgs such as python, ruby, perl, and the MS VC runtimes, that one needs and wants a choice as to whether to install the 32-bit or the 64-bit installer. And that's where the extra appended '_x86' or '_x64' comes in.

The one pkg I was not 100% sure if I made the right judgment call was the '7zip', as-is it will always install the correct bitness of the OS, but maybe it is in the same category as python, etc, where some people might want to differentiate or choose between installing the 32-bit or the 64-bit version.
