### ISSUE TITLE
pkg.list_pkgs is incredibly slow when there are many packages installed

### ISSUE THREAD

**Issue by lorengordon** [saltstack/salt-winrepo#60]
It takes a very long time for pkg.list_pkgs to complete when there are a lot of packages installed. For example, I've been doing a little testing with salt directly on my personal laptop, and I used powershell to time the command taking over 40 minutes to complete. Granted, I have 161 installed programs and 96 installed updates, but still...

PS >Measure-Command -Expression {Start-Process C:\salt\salt-call.exe -ArgumentList "--local pkg.list_pkgs" -NoNewWindow -PassThru -Wait}
Days              : 0
Hours             : 0
Minutes           : 42
Seconds           : 46
Milliseconds      : 889
Ticks             : 25668891551
TotalDays         : 0.0297093652210648
TotalHours        : 0.713024765305555
TotalMinutes      : 42.7814859183333
TotalSeconds      : 2566.8891551
TotalMilliseconds : 2566889.1551

**Comment by UtahDave** [comment]
Wow, that does seem horribly excessive. @twangboy has done quite a bit of work on the pkg module on Windows recently.  Have you tested on a newer Salt version such as 2015.5.3?

**Comment by lorengordon** [comment]
Heh, I forgot I even opened this issue. I'll test again this evening with a current version of salt. (Pretty sure I was using 2014.1 for this test.)

**Comment by UtahDave** [comment]
Sorry for not seeing this issue sitting here for almost a year. I didn't see it among the other issues.  That's embarrassing.

If this is still a problem, let's copy this issue over to the main Salt repo since this is more of a problem with Salt's internal pkg module and not so much with this software pkg repo.

**Comment by lorengordon** [comment]
No worries, I was just getting started with salt and GitHub at the time and probably didn't even realize I was submitting the issue in the wrong place. I understand the difference now. :grinning:

**Comment by lorengordon** [comment]
Much better now! Under 10 seconds.

```
PS >Measure-Command -Expression {Start-Process C:\salt\salt-call.bat -ArgumentList "--local pkg.list_pkgs" -NoNewWindow -PassThru -Wait}

<...snip.../>

Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 9
Milliseconds      : 100
Ticks             : 91005158
TotalDays         : 0.000105330043981481
TotalHours        : 0.00252792105555556
TotalMinutes      : 0.151675263333333
TotalSeconds      : 9.1005158
TotalMilliseconds : 9100.5158
```
