### ISSUE TITLE
putty.sls is broken. Bad format for 0.66 version

### ISSUE THREAD

**Issue by rterbush** [saltstack/salt-winrepo#606]
https://github.com/saltstack/salt-winrepo/blob/master/putty.sls#L2

Missing version number on line #2.

Causes genrepo to blow up. Rather big issue, especially since I seem to get this repo automatically and don't need it in my 2015.8.x environment.

This should be a quick fix for any regular contributor. If needed, happy to put together a pull request.

**Comment by TheBigBear** [comment]
@rterbush thanks for reporting this. Sorry, this was my mistake, bad copy and paste and a hasty commit.

**Comment by rterbush** [comment]
Have never done that myself... :monkey_face:
