### ISSUE TITLE
Duplicate full_name/version items in repo

### ISSUE THREAD

**Issue by johnccfm** [saltstack/salt-winrepo#612]
This is related to a PR I sent, https://github.com/saltstack/salt-winrepo/pull/585

I need a sanity check here, because I think this is majorly broken but perhaps I'm totally wrong.

The win_pkg module identifies software by matching on the full_name and version data **only**. It seems to scan its list of known packages until it finds the first match. If there are duplicates in this package DB, then the match you get seems to be indeterminate.

The results of this is that if you have two packages defined with the same full_name and version ... say npp and npp_x86 ... then calling 

```
pkg.install npp
```

on the minion might fail. 

Doing

```
pkg.list_pkgs
```

might show "npp_x86" as installed. This means that salt will always treat that install as failed, even though the software has installed successfully.

A side-effect of this (for this old pre-2015.8 repo at least) is that you can't have separate packages for x86 and x64 software unless their installed full_name differs, e.g. "Foobar" and "Foobar (64-bit)". For certain cases where I really, really need this I've been forced to use a free MSI editor to change the name (the example in my case being the MySQL ODBC drivers, where I need 64 and 32 bit versions installed on 64 bit machines, since I have apps of both architectures running).

Can someone confirm whether this really _is_ a problem as I think it is, or am I totally wide of the mark?

**Comment by johnccfm** [comment]
Since this repo is now effectively a legacy thing, and since 32-bit Windows is mostly a legacy thing, I'd suggest the fix (where clashes occur) is just to remove the 32-bit package. It is likely to have very little impact.

**Comment by TheBigBear** [comment]
@johnccfm You got it. It is Indeed a problem exactly as you describe it.

**Comment by johnccfm** [comment]
I've just (as of yesterday) bumped my Windows minions to 2015.8.1 so it doesn't affect me directly any more.

I think my PR might need updating because time has passed, but do you think the approach is reasonable? I'm not sure which is the better way to look at it. Is it better to have a bigger selection of packages where you have to ignore the return status of the install state (and can't rely on list_pkgs or guarantee that you can uninstall or upgrade packages), or is it better to have a smaller number where the install/query/remove works properly?

**Comment by twangboy** [comment]
@johnccfm Your master will also need to be 2015.8.1 to work with the new winrepo.

**Comment by johnccfm** [comment]
@twangboy yeah thanks, it is! I upgraded everything to 2015.8.0 and then hit the problem with the HTTP downloads for the Windows repo being broken, so rolled the Windows minions only back to 2015.5.5 temporarily. Now I've upgraded everything to 2015.8.1.
