### ISSUE TITLE
Docker toolbox/boot2docker

### ISSUE THREAD

**Issue by DavidJFelix** [saltstack/salt-winrepo#770]
https://www.docker.com/products/docker-toolbox

**Comment by TheBigBear** [comment]
@DavidJFelix how is this a salt-winrepo issue? Can you give abit of context? This sems like a 'random' link i the middle of a packaging repo.

Would you like a salt-winrepo sls installer for it written? If you do, can you do some research on how to quietly install this, please?

Even when using all the 'silent' switches for a Inno-Installer, known to me, this one comes up with severeal user prompts, which means it can't really be installed by salt-winrepo.

The Inno-Installer switches I tried are:
/VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP-

**Comment by DavidJFelix** [comment]
This is just an issue tracking docker toolbox win report inclusion since it's not included but a desirable package. I managed to find the inno installer script but I'm not sure what I'm looking for https://github.com/docker/toolbox/blob/master/windows/Toolbox.iss

**Comment by TheBigBear** [comment]
@DavidJFelix, basically try installing it on a clean windows machine and apply all the known 'silent' switches to the installer as in:

```DockerToolbox-1.10.2.exe /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP-```

and then watch the supposedly silent and no user interaction install, and every time it asks for user feedback, make a note of it, and then try to eliminate it.  The reason being, that any single UI question will stall and hold the install and salt-winrepo can't install it, as it runs in the background.

From memory I think there is at least four or more times, that it stops for user interaction. 

Some of them may even be for pre-requirements, it has quite a list of requirements that it will install if they are not already there. (and on a new VM you should find all of them)
