### ISSUE TITLE
WinPcap have no 'silent' installation

### ISSUE THREAD

**Issue by romanovna** [saltstack/salt-winrepo#810]
Actually, winpcap_install.exe have no silent installation, so it may be a little bit confusing, when your state takes too long to finish.

**Comment by twangboy** [comment]
Then it can't be installed using `pkg.install`

**Comment by romanovna** [comment]
Just some info about WinPcap and silent installation, hope this would be helpful
http://paperlined.org/apps/wireshark/winpcap_silent_install.html

**Comment by hsluoyz** [comment]
Hi.

You would like to try Npcap: https://github.com/nmap/npcap.

It's another fork of WinPcap with multiple new features, including silent installation.
